### numpy

#### 1d array

In [21]:
import numpy as np               #1d array
array=np.array([1,2,3,4,5,6])
print(array)



[1 2 3 4 5 6]


In [22]:
import numpy as np
array=np.array([1,2,3,4,5,6])
print(array.shape)

(6,)


#### 2d array

In [5]:
darray=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(darray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
darray=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(darray)
print(darray.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


#### to find out dimension of array

In [7]:
print(darray.ndim)

2


#### 3d array

In [10]:

tarray=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(tarray)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [11]:
print(tarray.ndim)

3


#### to find out size of array

In [12]:
print(tarray.size)

9


In [18]:
print(array.size)

6


#### to access element of array

In [17]:
print(array[1])

2


#### slicing of array

In [20]:
print(array[2:5])

[3 4 5]


#### reshape()

In [ ]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 element

In [23]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Convert the following 1-D array with 12 elements into a 3-D array.

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements

In [24]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### to find out the data type of the array

In [3]:
print(arr.dtype)

NameError: name 'arr' is not defined

#### access single element from an array

In [4]:
print(array[1])

NameError: name 'array' is not defined