# linear algebra and machine learning

## vectors and dot products

In [45]:
import numpy as np


In [46]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1,arr2)

[1 2 3] [4 5 6]


## dot products

In [47]:
print(np.dot(arr1,arr2))

32


### matrices and operations (2d)

In [48]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


## addition and substraction

In [49]:
print(a+b)

[[ 6  8]
 [10 12]]


In [50]:
print("substraction of arr3 or arr4 \n",a-b)

substraction of arr3 or arr4 
 [[-4 -4]
 [-4 -4]]


## multiplication and division

In [51]:
print("multiplicatiom of arr3 or arr4 \n",a*b)

multiplicatiom of arr3 or arr4 
 [[ 5 12]
 [21 32]]


In [52]:
print("division of arr3 or arr4 \n",a/b)

division of arr3 or arr4 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


## 3d array

In [53]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
d=np.array([[[2,3,4],[5,6,7],[8,9,1]]])
print(c)
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[2 3 4]
  [5 6 7]
  [8 9 1]]]


In [54]:
print("addition of c and d \n",c+d)

addition of c and d 
 [[[ 3  5  7]
  [ 9 11 13]
  [15 17 10]]]


In [55]:
print("substraction of c and d \n",c-d)

substraction of c and d 
 [[[-1 -1 -1]
  [-1 -1 -1]
  [-1 -1  8]]]


In [56]:
print(c)
print(d)
print("division of c and d \n",c*d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[2 3 4]
  [5 6 7]
  [8 9 1]]]
division of c and d 
 [[[ 2  6 12]
  [20 30 42]
  [56 72  9]]]


## dot product of 2d array

In [57]:
print(arr1@arr2)

32


In [58]:
print(c)
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[2 3 4]
  [5 6 7]
  [8 9 1]]]


In [59]:
print(c@d)


[[[ 36  42  21]
  [ 81  96  57]
  [126 150  93]]]


## TRANSPOSE OF MATRIX

In [60]:
print(a.T)

[[1 3]
 [2 4]]


In [61]:
print(c)
print(c.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]

 [[3]
  [6]
  [9]]]


## identity matrix

In [62]:
I=np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [63]:
I1=np.eye(3)
print(I1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [64]:
I2=np.eye(2)
print(I2)

[[1. 0.]
 [0. 1.]]


## inverse matrix

In [65]:
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [66]:
e=np.array([[2,3],[4,5]])
f=np.array([[6,7],[8,9]])
print(e)
print(f)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [67]:
e_inv = np.linalg.inv(e)
print(e)
print(e_inv)

[[2 3]
 [4 5]]
[[-2.5  1.5]
 [ 2.  -1. ]]


In [75]:
h=np.array([[[4,5,16],[9,18,7],[1,2,3]]])
h_inv=np.linalg.inv(h)
print(h)
print(h_inv)

[[[ 4  5 16]
  [ 9 18  7]
  [ 1  2  3]]]
[[[ 0.66666667  0.28333333 -4.21666667]
  [-0.33333333 -0.06666667  1.93333333]
  [ 0.         -0.05        0.45      ]]]


## determinant of matrix

In [70]:
e_inv = np.linalg.det(e)
print(e)
print(e_inv)

[[2 3]
 [4 5]]
-2.0


In [71]:
arr=np.array([[1,-2,3],[2,0,3],[1,5,4]])
print(arr)
e_inv = np.linalg.det(arr)
print(e_inv)

[[ 1 -2  3]
 [ 2  0  3]
 [ 1  5  4]]
24.999999999999996


## eigen value and eigen vector

In [72]:
matrix=np.array([[4,2],[3,5]])
eigenvalues,eigenvectors=np.linalg.eig(matrix)
print("EIGENVALUES:",eigenvalues)
print("\nEIGENVECTORS:",eigenvectors)

EIGENVALUES: [2. 7.]

EIGENVECTORS: [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


# 3d

In [73]:
matrix1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
eigenvalues,eigenvectors=np.linalg.eig(matrix1)
print("EIGENVALUES:",eigenvalues)
print("\nEIGENVECTORS:",eigenvectors)

EIGENVALUES: [[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]]

EIGENVECTORS: [[[-0.23197069 -0.78583024  0.40824829]
  [-0.52532209 -0.08675134 -0.81649658]
  [-0.8186735   0.61232756  0.40824829]]]
