## homework

In [6]:
import numpy as np
single_dimarray=np.array([1,2,3,4,5,6])
print(single_dimarray)
print(single_dimarray.shape)
print(single_dimarray.size)
print(single_dimarray.ndim)
print(single_dimarray.reshape)

[1 2 3 4 5 6]
(6,)
6
1
<built-in method reshape of numpy.ndarray object at 0x00000246987052F0>


In [14]:
two_dimarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_dimarray)
print(two_dimarray.shape)
print(two_dimarray.size)
print(two_dimarray.ndim)
print(two_dimarray.reshape(3,3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
three_dimarray=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(three_dimarray)
print(three_dimarray.shape)
print(three_dimarray.size)
print(three_dimarray.ndim)
print(three_dimarray.reshape(3,3))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
9
3
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### reshape()

#### 2d array

In [23]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
print(arr)
newarr=arr.reshape(4,3)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


##### 3d array

In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
print(arr)
newarr=arr.reshape(2,3,2)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### to find out data type of arrayy

In [27]:
print(single_dimarray.dtype)

int64


#### access single element from an array

In [26]:
print(single_dimarray[4])

5


#### access single element from mulidimensional array

In [28]:
print(two_dimarray)
print(two_dimarray[0,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


#### slicing of array

In [30]:
print(single_dimarray)
print(single_dimarray[2:5])

[1 2 3 4 5 6]
[3 4 5]


#### to update existing array

In [36]:
print(single_dimarray)
single_dimarray[4]=55
print(single_dimarray)

[1 2 3 4 5 6]
[ 1  2  3  4 55  6]


In [37]:
print(single_dimarray)
single_dimarray[4]=66
print(single_dimarray)


[ 1  2  3  4 55  6]
[ 1  2  3  4 66  6]


#### slicing in multidimensional array

In [38]:
print(two_dimarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
print(two_dimarray[0:2])

[[1 2 3]
 [4 5 6]]


In [41]:
print(two_dimarray[:,:2])

[[1 2]
 [4 5]
 [7 8]]


In [43]:
print(two_dimarray[:2])

[[1 2 3]
 [4 5 6]]


#### addition

In [44]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

result = array1 + array2
print(result) 


[5 7 9]


#### substraction

In [45]:
import numpy as np

array1 = np.array([10, 20, 30])
array2 = np.array([4, 5, 6])

result = array1 - array2
print(result) 

[ 6 15 24]


#### multiplication

In [46]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

result = array1 * array2
print(result) 

[ 4 10 18]


#### division

In [48]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

result = array1 / array2
print(result) 

[0.25 0.4  0.5 ]


#### 2d array

In [1]:
import numpy as np

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])

result = array1 * array2
print(result) 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [2]:
import numpy as np

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])

result = array1 / array2
print(result) 

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


In [ ]:
import numpy as np

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])

result = array1 - array2
print(result) 

In [4]:
import numpy as np

array1 = np.array([[12,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])

result = array1 + array2
print(result) 

[[23 14 16]
 [18 20 22]
 [24 26 28]]


#### 3d array

In [5]:
array1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array2 = np.array([[[11,12,13],[14,15,16],[17,18,19]]])
result = array1 + array2
print(result)

[[[12 14 16]
  [18 20 22]
  [24 26 28]]]


In [8]:
array1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
array2 = np.array([[[11,12,13],[14,15,16],[17,18,19]]])
result = array1 * array2
print(result)

[[[ 11  24  39]
  [ 56  75  96]
  [119 144 171]]]


In [9]:
array1 = np.array([[[11,12,13],[14,15,16],[17,18,19]]])
array2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
result = array1 - array2
print(result)


[[[10 10 10]
  [10 10 10]
  [10 10 10]]]


In [15]:
import numpy as np
array1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array1)
print(array1[0:1,0:2,:2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2]
  [4 5]]]


In [ ]:
import numpy as np
array1 = np.array([[1,2,3,4,5])



In [8]:
array1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print (array1)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#### print the highest number using for loop

In [1]:
import numpy as np 
arr=np.array([10,20,50,80,40,30])
max=arr[0]
for i in arr:
    if i>max:
        max=i
print(f"{max} is greater")        

80 is greater


#### print the smallest number using for loop

In [3]:
import numpy as np 
arr=np.array([10,20,50,80,40,30])
min=arr[0]
for i in arr:
    if i<min:
        min=i
print(f"{min} is smallerr")     

10 is smallerr


###    mean of an array

In [4]:
import numpy as np 
arr=np.array([10,20,50,80,40])
print(arr.mean())

40.0


###    maximum element in an array

In [5]:
import numpy as np 
arr=np.array([10,20,50,80,40])
print(arr.max())

80


In [7]:
import numpy as np 
arr=np.array([10,20,50,80,40])
for i in arr:
    print(i)
    

10
20
50
80
40


In [ ]:
import numpy as np 
arr=np.array([10,20,50,80,40])
for i in arr:
    print(i)
    

In [6]:
import numpy as np 
arr=np.array([10,20,50,80,30])

for i in arr:
    max=arr[0]
    if i >=max:
        max=i
print(max)
    

10


#### minimum element in an array

In [2]:
min=arr[0]
for i in arr:
    if i<min:
        min=i
print(min)        

10


### standerd deviation

In [13]:
print(sum.std())

AttributeError: 'builtin_function_or_method' object has no attribute 'std'

### sorting of an array

In [14]:
print(np.sort(arr))

[10 20 40 50 80]
